openapi: "3.0.0"
info:
  version: 1.0.0
  title: Swagger Hello Unicorn Bank
  license:
    name: MIT
servers:
  - url: http://localhost:8080/api/v1
paths:
  /ping:
    get:
      summary: Quick Ping Check
      operationId: ping
      tags:
        - ping
      responses:
        '200':
          description: A ping
          content:
            application/json:    
              schema:
                $ref: "#/components/schemas/Ping"
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
  /account:
    get:
      summary: Get Account
      operationId: getAccount
      tags:
        - account
      parameters:
        - name: id
          in: path
          description: ID of Account to fetch
          required: true
          schema:
            type: string
            format: uuid 
      responses:
        '200':
          description: List of Account
          content:
            application/json:    
              schema:
                $ref: "#/components/schemas/Account"
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
  /payment:
    post:
      summary: Post a Payment
      operationId: postPayment
      tags:
        - payment
      responses:
        '200':
          description: Payment Accepted
          content:
            application/json:    
              schema:
                $ref: "#/components/schemas/Payment"
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"    
components:
  schemas:
    Accounts:
      type: array
      items:
        $ref: '#/components/schemas/Account'
    Account:
      type: object
      required:
        - id
        - name
      properties:
        id:
          type: string
          format: uuid
        name:
          type: string
        balance:
          type: number
          format: double
        currency:
          type: string
          enum: [GBP, USD]
    Payment:
      type: object
      required:
        - id
        - fromAccountId
        - toAccountId
        - amount
        - currency
      properties:
        id:
          type: string
          format: uuid
        reference:
          type: string
        fromAccountId:
          type: string
          format: uuid
        toAccountId:
          type: string
          format: uuid
        amount:
          type: number
          format: double
          minimum: 0
        currency:
          type: string
          enum: [GBP, USD]
    Ping:
      type: object
      required:
        - id
        - message
      properties:
        id:
          type: string
          format: uuid
        message:
          type: string
    Error:
      type: object
      required:
        - code
        - message
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string