openapi: "3.0.0"
info:
  version: 1.0.0
  title: Swagger Hello Unicorn Bank
  license:
    name: MIT
servers:
  - url: http://localhost:8080/api/v1
paths:
  /ping:
    get:
      summary: Quick Ping Check
      operationId: ping
      tags:
        - ping
      responses:
        '200':
          description: A ping
          content:
            application/json:    
              schema:
                $ref: "#/components/schemas/Ping"
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
components:
  schemas:
    Ping:
      type: object
      required:
        - id
        - message
      properties:
        id:
          type: string
          format: uuid
        message:
          type: string
    Error:
      type: object
      required:
        - code
        - message
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string